name: video_launcher
description: Fullscreen video launcher plugin
version: 0.2.0
author: Erick Ghaumez <rx.devlabz@gmail.com>
homepage: https://github.com/rxlabz/flutter_video_launcher

flutter:
  plugin:
    androidPackage: bz.rxla.video_launcher
    pluginClass: VideoLauncherPlugin

dependencies:
  flutter:
    sdk: flutter
